language: rust
sudo: false

rust:
  - stable
  - beta

script:
  - cargo build --verbose
  # --all-targets is required because our tests are in the examples, which normally don't get run
  # --nocapture is required to verify the stdout of the tests with gag-rs
  - cargo test --all-targets --verbose -- --nocapture

jobs:
  include:
    - rust: nightly
      script:
        - cargo build --verbose
        - cargo test --all-targets --verbose -- --nocapture

        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo build --verbose
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --all-targets --verbose -- --nocapture

        - cargo update -Z minimal-versions
        - cargo build --verbose
        - cargo test --all-targets --verbose -- --nocapture

        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo build --verbose
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --all-targets --verbose -- --nocapture
