language: rust
sudo: false

rust:
  - stable
  - beta

script:
  - cargo build --verbose
  # --nocapture is required to verify the stdout of the tests with gag-rs
  - cargo test --verbose -- --nocapture

jobs:
  include:
    - rust: nightly
      script:
        - cargo build --verbose
        - cargo test --verbose -- --nocapture

        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo build --verbose
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --verbose -- --nocapture

        - cargo update -Z minimal-versions
        - cargo build --verbose
        - cargo test --verbose -- --nocapture

        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo build --verbose
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --verbose -- --nocapture
